explict metric grouping configuration and group readiness
app-sre/signalfx-prometheus-exporter pull request #17
Opened 2022-03-06 10:18 UTC by geoberle

introduce configuration options for metric scraping based on labels to improve
blackbox-exporter compatibility mode. grouping options are now explicit and
include options to define when a group of metrics is ready for scraping, e.g.
number of metrics available within a group or age of metrics in a group.

the async metric delivery mode of signalfx makes it necessary to handle situations
when metrics are yet missing (e.g. cold cache on process startup). the `groupReadyConditions` config
section provides options to declare the behaviour for such situations, failing a
scrape on the `/metric/$label_name` endpoint in situations when the conditions
are not satisfied. this will result in the default metric `up` on the scraper side
to highlight that metrics could not be aquired. depending on the situation, this
behaviour might be better than scraping incomplete or outdated metrics.

the following configuration enables filtered scraping based on the
specified label `label`. also, at least 2 metrics must be present after filtering
on the label. otherwise the scrape endpoint will fail with a descriptive error.

```yaml
grouping:
- label: label
  groupReadyConditions:
    minMetrics: 2
```

for filtering on the provided label, the url parameter `target` is used. this
provides compatibility with blackbox-exporter and enables the use of the `Probe`
CRD that comes with the Prometheus operator.

a valid scrape URL looks like this:

`:9091/metrics/label?target=value`

Signed-off-by: Gerd Oberlechner <goberlec@redhat.com>

2022-03-07 13:13 UTC, janboll requested changes

2022-03-07 13:13 UTC, janboll commented on config/config.go
> +	MinMetrics int `yaml:"minMetrics"`
Is -10 a valid value for this? Perhaps uint would be a better type? Is 0 valid?

2022-03-07 14:46 UTC, geoberle commented on README.md
> +the conditions are not satisfied. This will result in the default metric `up`
just per group

2022-03-07 15:06 UTC, geoberle commented on README.md
> -The `:9091/probe/$label?target=$value` endpoint can be used to filter metrics based on a Prometheus  `$label` with value `$value`, e.g. `http://localhost:9091/probe/instance?target=my_instance`
added in [ec4ad98](https://github.com/app-sre/signalfx-prometheus-exporter/pull/17/commits/ec4ad987ba5528b512912eebc1d9aca1cb7608d7)

2022-03-07 15:06 UTC, geoberle commented on config/config.go
> +type GroupingConfig struct {
good point - 8a4cb8a

2022-03-07 15:06 UTC, geoberle commented on config/config.go
> +	ReadyConditions GroupReadyConditions `yaml:"groupReadyConditions"`
fixed in 8a4cb8a

2022-03-07 15:07 UTC, geoberle commented on README.md
> +where the `target` query paremter supplies the value to filter on.
fixed

2022-03-07 15:07 UTC, geoberle commented on README.md
> +Metrics can also be scraped based on a metric labels. This can be enabled by providing
fixed

2022-03-07 15:08 UTC, geoberle commented on serve/registry_test.go
> +package serve_test
yes i need to write more tests. easier now, since you made the first step ❤️

2022-03-07 21:41 UTC, geoberle commented on config/config.go
> +	MinMetrics int `yaml:"minMetrics"`
implemented uint and tests for it in [04620fb](https://github.com/app-sre/signalfx-prometheus-exporter/pull/17/commits/04620fb9af4e982142dcb4471ba3a4c6a0d5379d)

2022-03-08 07:43 UTC, janboll approved these changes

2022-03-08 09:36 UTC, merged